### ISSUE TITLE
Disable password autocompletion in webadmin user settings

### ISSUE THREAD

**Issue by sagamusix** [znc/znc#1163]
When trying to edit my user settings in ZNC 1.6.1, I randomly got an "Invalid user settings" error when trying to save them in the web interface. It turns out that Firefox was filling in my stored password despite the autocomplete=off markup, and as a consequence it didn't match the password confirmation input field.
ZNC should give more user-friendly feedback by actually indicating which settings were invalid (in this case: "Passwords do not match" or something similar).

**Comment by Mikaela** [comment]
Do you happen to be using patched ZNC (the SSL patch or some third party webadmin theme (firre is especially problematic with these issues))? If not, you are probably trying to set some setting as invalid such as emptying realname.

ICU support doesn't affect anything else than charset and if you want it, install `libicu-dev` (you didn't read the bug reporting guidelines as your OS is missing so I am doing Debian assumption) and recompile ZNC.

**Comment by sagamusix** [comment]
Nevermind, I might have found the issue - I do have the main login for ZNC stored in the browser's password manager, but despite the autocomplete=off markup, Firefox seems to keep filling in the password when first visting the page and as such it doesn't match the empty confirm password field.

Nevertheless, it would have been useful if ZNC actually told me e.g. that passwords don't match, rather than making me guess which of the dozens of options on this page is not configured correctly.

**Comment by Mikaela** [comment]
Please open separate issue for that or make it clear in the title what this issue is about.

**Comment by sagamusix** [comment]
I've edited the title and initial description to be more clear.

**Comment by Mikaela** [comment]
I would change the title to `Say "Passwords don't match" instead of "Invalid user settings"`, but maybe the current one is more clear as there are more things that can be invalid too.

**Comment by sagamusix** [comment]
Yes, that's my point with the title: ZNC knows exactly which settings are invalid (otherwise it could not emit this error message), so it should tell the user exactly what is wrong - not only for the password fields.

**Comment by walliski** [comment]
:+1: for this. Noticed this today as well, would be nice to have!

**Comment by LukeSwart** [comment]
:+1: Thank you! I have been having this problem for a while, but thanks to this issue, I finally know the source of the problem.

**Comment by xintron** [comment]
Ran into this issue today as well (in Firefox). Might be worth trying some of the tricks mentioned here: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion - especially the `autocomplete="nope"` to trick the browser to not autocomplete.

My guess is that it would also be possible to work around this by using a different name for the input field: `Password: <input name="something_random" autocomplete="nope" />`.

**Comment by bionicrm** [comment]
Same issue happened to me. :+1: on this issue.

**Comment by DarthGandalf** [comment]
@xintron `autocomplete="nope"` still causes FireFox to autocomplete :-(

**Comment by sagamusix** [comment]
@DarthGandalf: The title of the issue was chosen because it was not just about the password field (even though most people seemed to only be concerned about that). Your commit only fixed that part of the problem, so I think the issue should remain open under the old title. There are still other situations where the "invalid user settings" message is not descriptive enough.

**Comment by DarthGandalf** [comment]
@sagamusix ok. I fixed both issues though, in 2 commits.

**Comment by GaryMatthews** [comment]
this is annoying. until i actually stumbled across this and found out that i have to blank the password field i was deleting and resetting up accounts just to get back to changing settings and is still an issue with the latest version of znc. an error messages "SHOULD" always return the setting that caused the error not just that an error occurred and leave it at that. this is a bug still present in the latest version.
